/** THIS IS AN AUTOMATICALLY GENERATED FILE.
 *  DO NOT MODIFY BY HAND!!
 *
 *  Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __XboxMap_hpp__
#define __XboxMap_hpp__



class XboxMap
{
    public:
        int8_t     a;

        int8_t     b;

        int8_t     x;

        int8_t     y;

        int8_t     leftShoulder;

        int8_t     rightShoulder;

        int8_t     leftStick;

        int8_t     rightStick;

        int8_t     start;

        int8_t     back;

        int8_t     dpadUp;

        int8_t     dpadDown;

        int8_t     dpadLeft;

        int8_t     dpadRight;

        float      leftX;

        float      leftY;

        float      rightX;

        float      rightY;

        float      leftTrigger;

        float      rightTrigger;

        int32_t    error_flag;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~XboxMap() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "XboxMap"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int XboxMap::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int XboxMap::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t XboxMap::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t XboxMap::getHash()
{
    static int64_t hash = (int64_t)_computeHash(NULL);
    return hash;
}

const char* XboxMap::getTypeName()
{
    return "XboxMap";
}

int XboxMap::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos_byte = 0;
    int thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->a, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->b, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->x, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->y, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftShoulder, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightShoulder, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftStick, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightStick, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->start, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->back, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadUp, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadDown, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadLeft, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadRight, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftX, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftY, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightX, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightY, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftTrigger, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightTrigger, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->error_flag, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

int XboxMap::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos_byte = 0;
    int thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->a, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->b, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->x, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->y, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftShoulder, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightShoulder, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftStick, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightStick, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->start, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->back, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadUp, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadDown, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadLeft, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->dpadRight, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftX, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftY, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightX, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightY, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->leftTrigger, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __float_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->rightTrigger, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &this->error_flag, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

uint32_t XboxMap::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

#if defined(__clang__)
__attribute__((no_sanitize("integer")))
#endif
uint64_t XboxMap::_computeHash(const __zcm_hash_ptr*)
{
    uint64_t hash = (uint64_t)0xd08746e1b93ec287LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
