// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ip_service.proto
#ifndef GRPC_ip_5fservice_2eproto__INCLUDED
#define GRPC_ip_5fservice_2eproto__INCLUDED

#include "ip_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ipservice {

class IpService final {
 public:
  static constexpr char const* service_full_name() {
    return "ipservice.IpService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::ipservice::IpReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ipservice::IpReply>> AsyncSendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ipservice::IpReply>>(AsyncSendIpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ipservice::IpReply>> PrepareAsyncSendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ipservice::IpReply>>(PrepareAsyncSendIpRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest* request, ::ipservice::IpReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest* request, ::ipservice::IpReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ipservice::IpReply>* AsyncSendIpRaw(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ipservice::IpReply>* PrepareAsyncSendIpRaw(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::ipservice::IpReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ipservice::IpReply>> AsyncSendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ipservice::IpReply>>(AsyncSendIpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ipservice::IpReply>> PrepareAsyncSendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ipservice::IpReply>>(PrepareAsyncSendIpRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest* request, ::ipservice::IpReply* response, std::function<void(::grpc::Status)>) override;
      void SendIp(::grpc::ClientContext* context, const ::ipservice::IpRequest* request, ::ipservice::IpReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ipservice::IpReply>* AsyncSendIpRaw(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ipservice::IpReply>* PrepareAsyncSendIpRaw(::grpc::ClientContext* context, const ::ipservice::IpRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendIp_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendIp(::grpc::ServerContext* context, const ::ipservice::IpRequest* request, ::ipservice::IpReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendIp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendIp() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendIp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendIp(::grpc::ServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendIp(::grpc::ServerContext* context, ::ipservice::IpRequest* request, ::grpc::ServerAsyncResponseWriter< ::ipservice::IpReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendIp<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendIp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendIp() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ipservice::IpRequest, ::ipservice::IpReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ipservice::IpRequest* request, ::ipservice::IpReply* response) { return this->SendIp(context, request, response); }));}
    void SetMessageAllocatorFor_SendIp(
        ::grpc::MessageAllocator< ::ipservice::IpRequest, ::ipservice::IpReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ipservice::IpRequest, ::ipservice::IpReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendIp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendIp(::grpc::ServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendIp(
      ::grpc::CallbackServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendIp<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendIp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendIp() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendIp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendIp(::grpc::ServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendIp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendIp() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendIp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendIp(::grpc::ServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendIp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendIp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendIp() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendIp(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendIp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendIp(::grpc::ServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendIp(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendIp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendIp() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ipservice::IpRequest, ::ipservice::IpReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ipservice::IpRequest, ::ipservice::IpReply>* streamer) {
                       return this->StreamedSendIp(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendIp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendIp(::grpc::ServerContext* /*context*/, const ::ipservice::IpRequest* /*request*/, ::ipservice::IpReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendIp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ipservice::IpRequest,::ipservice::IpReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendIp<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendIp<Service > StreamedService;
};

}  // namespace ipservice


#endif  // GRPC_ip_5fservice_2eproto__INCLUDED
