# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_pb2 as robot__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotServiceStub(object):
    """*
    统一服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlVideo = channel.unary_unary(
                '/robot.RobotService/ControlVideo',
                request_serializer=robot__pb2.ControlSignalRequest.SerializeToString,
                response_deserializer=robot__pb2.ControlSignalResponse.FromString,
                _registered_method=True)
        self.GetRecorderState = channel.unary_unary(
                '/robot.RobotService/GetRecorderState',
                request_serializer=robot__pb2.RecorderStateRequest.SerializeToString,
                response_deserializer=robot__pb2.RecorderStateResponse.FromString,
                _registered_method=True)


class RobotServiceServicer(object):
    """*
    统一服务
    """

    def ControlVideo(self, request, context):
        """Control video stream (connect/disconnect and handle SDP negotiation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecorderState(self, request, context):
        """Query the current state and configuration of all recorders (cameras)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlVideo,
                    request_deserializer=robot__pb2.ControlSignalRequest.FromString,
                    response_serializer=robot__pb2.ControlSignalResponse.SerializeToString,
            ),
            'GetRecorderState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecorderState,
                    request_deserializer=robot__pb2.RecorderStateRequest.FromString,
                    response_serializer=robot__pb2.RecorderStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.RobotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """*
    统一服务
    """

    @staticmethod
    def ControlVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/ControlVideo',
            robot__pb2.ControlSignalRequest.SerializeToString,
            robot__pb2.ControlSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecorderState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotService/GetRecorderState',
            robot__pb2.RecorderStateRequest.SerializeToString,
            robot__pb2.RecorderStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
