/** THIS IS AN AUTOMATICALLY GENERATED FILE.
 *  DO NOT MODIFY BY HAND!!
 *
 *  Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __RobotInfo_hpp__
#define __RobotInfo_hpp__

#include <string>


class RobotInfo
{
    public:
        std::string robot_name;

        std::string robot_type;

        std::string firmware_version;

        std::string hardware_version;

        std::string software_version;

        std::string manufacturer;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~RobotInfo() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "RobotInfo"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int RobotInfo::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int RobotInfo::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t RobotInfo::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t RobotInfo::getHash()
{
    static int64_t hash = (int64_t)_computeHash(NULL);
    return hash;
}

const char* RobotInfo::getTypeName()
{
    return "RobotInfo";
}

int RobotInfo::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos_byte = 0;
    int thislen;

    char* robot_name_cstr = (char*) this->robot_name.c_str();
    thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &robot_name_cstr, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    char* robot_type_cstr = (char*) this->robot_type.c_str();
    thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &robot_type_cstr, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    char* firmware_version_cstr = (char*) this->firmware_version.c_str();
    thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &firmware_version_cstr, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    char* hardware_version_cstr = (char*) this->hardware_version.c_str();
    thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &hardware_version_cstr, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    char* software_version_cstr = (char*) this->software_version.c_str();
    thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &software_version_cstr, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    char* manufacturer_cstr = (char*) this->manufacturer.c_str();
    thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &manufacturer_cstr, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;

    return pos_byte;
}

int RobotInfo::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos_byte = 0;
    int thislen;

    int32_t __robot_name_len__;
    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &__robot_name_len__, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;
    if((uint32_t)__robot_name_len__ > maxlen - pos_byte) return -1;
    this->robot_name.assign(((const char*)buf) + offset + pos_byte, __robot_name_len__ - ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS);
    pos_byte += __robot_name_len__;

    int32_t __robot_type_len__;
    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &__robot_type_len__, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;
    if((uint32_t)__robot_type_len__ > maxlen - pos_byte) return -1;
    this->robot_type.assign(((const char*)buf) + offset + pos_byte, __robot_type_len__ - ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS);
    pos_byte += __robot_type_len__;

    int32_t __firmware_version_len__;
    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &__firmware_version_len__, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;
    if((uint32_t)__firmware_version_len__ > maxlen - pos_byte) return -1;
    this->firmware_version.assign(((const char*)buf) + offset + pos_byte, __firmware_version_len__ - ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS);
    pos_byte += __firmware_version_len__;

    int32_t __hardware_version_len__;
    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &__hardware_version_len__, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;
    if((uint32_t)__hardware_version_len__ > maxlen - pos_byte) return -1;
    this->hardware_version.assign(((const char*)buf) + offset + pos_byte, __hardware_version_len__ - ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS);
    pos_byte += __hardware_version_len__;

    int32_t __software_version_len__;
    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &__software_version_len__, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;
    if((uint32_t)__software_version_len__ > maxlen - pos_byte) return -1;
    this->software_version.assign(((const char*)buf) + offset + pos_byte, __software_version_len__ - ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS);
    pos_byte += __software_version_len__;

    int32_t __manufacturer_len__;
    thislen = __int32_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &__manufacturer_len__, 1);
    if(thislen < 0) return thislen; else pos_byte += thislen;
    if((uint32_t)__manufacturer_len__ > maxlen - pos_byte) return -1;
    this->manufacturer.assign(((const char*)buf) + offset + pos_byte, __manufacturer_len__ - ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS);
    pos_byte += __manufacturer_len__;

    return pos_byte;
}

uint32_t RobotInfo::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->robot_name.size() + ZCM_CORETYPES_INT32_NUM_BYTES_ON_BUS + ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS;
    enc_size += this->robot_type.size() + ZCM_CORETYPES_INT32_NUM_BYTES_ON_BUS + ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS;
    enc_size += this->firmware_version.size() + ZCM_CORETYPES_INT32_NUM_BYTES_ON_BUS + ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS;
    enc_size += this->hardware_version.size() + ZCM_CORETYPES_INT32_NUM_BYTES_ON_BUS + ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS;
    enc_size += this->software_version.size() + ZCM_CORETYPES_INT32_NUM_BYTES_ON_BUS + ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS;
    enc_size += this->manufacturer.size() + ZCM_CORETYPES_INT32_NUM_BYTES_ON_BUS + ZCM_CORETYPES_INT8_NUM_BYTES_ON_BUS;
    return enc_size;
}

#if defined(__clang__)
__attribute__((no_sanitize("integer")))
#endif
uint64_t RobotInfo::_computeHash(const __zcm_hash_ptr*)
{
    uint64_t hash = (uint64_t)0x5e3f1c4ff9dfdbe2LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
