// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_robot_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_robot_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_robot_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_robot_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_robot_2eproto;
namespace robot {
class ControlSignalRequest;
struct ControlSignalRequestDefaultTypeInternal;
extern ControlSignalRequestDefaultTypeInternal _ControlSignalRequest_default_instance_;
class ControlSignalResponse;
struct ControlSignalResponseDefaultTypeInternal;
extern ControlSignalResponseDefaultTypeInternal _ControlSignalResponse_default_instance_;
class RecorderStateRequest;
struct RecorderStateRequestDefaultTypeInternal;
extern RecorderStateRequestDefaultTypeInternal _RecorderStateRequest_default_instance_;
class RecorderStateResponse;
struct RecorderStateResponseDefaultTypeInternal;
extern RecorderStateResponseDefaultTypeInternal _RecorderStateResponse_default_instance_;
class RecorderStateResponse_CameraConfig;
struct RecorderStateResponse_CameraConfigDefaultTypeInternal;
extern RecorderStateResponse_CameraConfigDefaultTypeInternal _RecorderStateResponse_CameraConfig_default_instance_;
class RecorderStateResponse_CameraConfig_StreamSpec;
struct RecorderStateResponse_CameraConfig_StreamSpecDefaultTypeInternal;
extern RecorderStateResponse_CameraConfig_StreamSpecDefaultTypeInternal _RecorderStateResponse_CameraConfig_StreamSpec_default_instance_;
class RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics;
struct RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsicsDefaultTypeInternal;
extern RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsicsDefaultTypeInternal _RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics_default_instance_;
}  // namespace robot
PROTOBUF_NAMESPACE_OPEN
template<> ::robot::ControlSignalRequest* Arena::CreateMaybeMessage<::robot::ControlSignalRequest>(Arena*);
template<> ::robot::ControlSignalResponse* Arena::CreateMaybeMessage<::robot::ControlSignalResponse>(Arena*);
template<> ::robot::RecorderStateRequest* Arena::CreateMaybeMessage<::robot::RecorderStateRequest>(Arena*);
template<> ::robot::RecorderStateResponse* Arena::CreateMaybeMessage<::robot::RecorderStateResponse>(Arena*);
template<> ::robot::RecorderStateResponse_CameraConfig* Arena::CreateMaybeMessage<::robot::RecorderStateResponse_CameraConfig>(Arena*);
template<> ::robot::RecorderStateResponse_CameraConfig_StreamSpec* Arena::CreateMaybeMessage<::robot::RecorderStateResponse_CameraConfig_StreamSpec>(Arena*);
template<> ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* Arena::CreateMaybeMessage<::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace robot {

enum ControlSignalRequest_ActionType : int {
  ControlSignalRequest_ActionType_UNKNOWN = 0,
  ControlSignalRequest_ActionType_CONNECT = 1,
  ControlSignalRequest_ActionType_DISCONNECT = 2,
  ControlSignalRequest_ActionType_ControlSignalRequest_ActionType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ControlSignalRequest_ActionType_ControlSignalRequest_ActionType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ControlSignalRequest_ActionType_IsValid(int value);
constexpr ControlSignalRequest_ActionType ControlSignalRequest_ActionType_ActionType_MIN = ControlSignalRequest_ActionType_UNKNOWN;
constexpr ControlSignalRequest_ActionType ControlSignalRequest_ActionType_ActionType_MAX = ControlSignalRequest_ActionType_DISCONNECT;
constexpr int ControlSignalRequest_ActionType_ActionType_ARRAYSIZE = ControlSignalRequest_ActionType_ActionType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ControlSignalRequest_ActionType_descriptor();
template<typename T>
inline const std::string& ControlSignalRequest_ActionType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ControlSignalRequest_ActionType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ControlSignalRequest_ActionType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ControlSignalRequest_ActionType_descriptor(), enum_t_value);
}
inline bool ControlSignalRequest_ActionType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ControlSignalRequest_ActionType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ControlSignalRequest_ActionType>(
    ControlSignalRequest_ActionType_descriptor(), name, value);
}
// ===================================================================

class ControlSignalRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.ControlSignalRequest) */ {
 public:
  inline ControlSignalRequest() : ControlSignalRequest(nullptr) {}
  ~ControlSignalRequest() override;
  explicit PROTOBUF_CONSTEXPR ControlSignalRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ControlSignalRequest(const ControlSignalRequest& from);
  ControlSignalRequest(ControlSignalRequest&& from) noexcept
    : ControlSignalRequest() {
    *this = ::std::move(from);
  }

  inline ControlSignalRequest& operator=(const ControlSignalRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlSignalRequest& operator=(ControlSignalRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlSignalRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlSignalRequest* internal_default_instance() {
    return reinterpret_cast<const ControlSignalRequest*>(
               &_ControlSignalRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlSignalRequest& a, ControlSignalRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlSignalRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlSignalRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlSignalRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlSignalRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ControlSignalRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ControlSignalRequest& from) {
    ControlSignalRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlSignalRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.ControlSignalRequest";
  }
  protected:
  explicit ControlSignalRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ControlSignalRequest_ActionType ActionType;
  static constexpr ActionType UNKNOWN =
    ControlSignalRequest_ActionType_UNKNOWN;
  static constexpr ActionType CONNECT =
    ControlSignalRequest_ActionType_CONNECT;
  static constexpr ActionType DISCONNECT =
    ControlSignalRequest_ActionType_DISCONNECT;
  static inline bool ActionType_IsValid(int value) {
    return ControlSignalRequest_ActionType_IsValid(value);
  }
  static constexpr ActionType ActionType_MIN =
    ControlSignalRequest_ActionType_ActionType_MIN;
  static constexpr ActionType ActionType_MAX =
    ControlSignalRequest_ActionType_ActionType_MAX;
  static constexpr int ActionType_ARRAYSIZE =
    ControlSignalRequest_ActionType_ActionType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ActionType_descriptor() {
    return ControlSignalRequest_ActionType_descriptor();
  }
  template<typename T>
  static inline const std::string& ActionType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ActionType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ActionType_Name.");
    return ControlSignalRequest_ActionType_Name(enum_t_value);
  }
  static inline bool ActionType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ActionType* value) {
    return ControlSignalRequest_ActionType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSdpTypeFieldNumber = 2,
    kSdpFieldNumber = 3,
    kActionFieldNumber = 1,
  };
  // string sdp_type = 2;
  void clear_sdp_type();
  const std::string& sdp_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sdp_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sdp_type();
  PROTOBUF_NODISCARD std::string* release_sdp_type();
  void set_allocated_sdp_type(std::string* sdp_type);
  private:
  const std::string& _internal_sdp_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sdp_type(const std::string& value);
  std::string* _internal_mutable_sdp_type();
  public:

  // string sdp = 3;
  void clear_sdp();
  const std::string& sdp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sdp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sdp();
  PROTOBUF_NODISCARD std::string* release_sdp();
  void set_allocated_sdp(std::string* sdp);
  private:
  const std::string& _internal_sdp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sdp(const std::string& value);
  std::string* _internal_mutable_sdp();
  public:

  // .robot.ControlSignalRequest.ActionType action = 1;
  void clear_action();
  ::robot::ControlSignalRequest_ActionType action() const;
  void set_action(::robot::ControlSignalRequest_ActionType value);
  private:
  ::robot::ControlSignalRequest_ActionType _internal_action() const;
  void _internal_set_action(::robot::ControlSignalRequest_ActionType value);
  public:

  // @@protoc_insertion_point(class_scope:robot.ControlSignalRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sdp_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sdp_;
    int action_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// -------------------------------------------------------------------

class ControlSignalResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.ControlSignalResponse) */ {
 public:
  inline ControlSignalResponse() : ControlSignalResponse(nullptr) {}
  ~ControlSignalResponse() override;
  explicit PROTOBUF_CONSTEXPR ControlSignalResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ControlSignalResponse(const ControlSignalResponse& from);
  ControlSignalResponse(ControlSignalResponse&& from) noexcept
    : ControlSignalResponse() {
    *this = ::std::move(from);
  }

  inline ControlSignalResponse& operator=(const ControlSignalResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlSignalResponse& operator=(ControlSignalResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlSignalResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlSignalResponse* internal_default_instance() {
    return reinterpret_cast<const ControlSignalResponse*>(
               &_ControlSignalResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ControlSignalResponse& a, ControlSignalResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlSignalResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlSignalResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlSignalResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlSignalResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ControlSignalResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ControlSignalResponse& from) {
    ControlSignalResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlSignalResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.ControlSignalResponse";
  }
  protected:
  explicit ControlSignalResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kSdpTypeFieldNumber = 2,
    kSdpFieldNumber = 3,
  };
  // string status = 1;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string sdp_type = 2;
  void clear_sdp_type();
  const std::string& sdp_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sdp_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sdp_type();
  PROTOBUF_NODISCARD std::string* release_sdp_type();
  void set_allocated_sdp_type(std::string* sdp_type);
  private:
  const std::string& _internal_sdp_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sdp_type(const std::string& value);
  std::string* _internal_mutable_sdp_type();
  public:

  // string sdp = 3;
  void clear_sdp();
  const std::string& sdp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sdp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sdp();
  PROTOBUF_NODISCARD std::string* release_sdp();
  void set_allocated_sdp(std::string* sdp);
  private:
  const std::string& _internal_sdp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sdp(const std::string& value);
  std::string* _internal_mutable_sdp();
  public:

  // @@protoc_insertion_point(class_scope:robot.ControlSignalResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sdp_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sdp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// -------------------------------------------------------------------

class RecorderStateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.RecorderStateRequest) */ {
 public:
  inline RecorderStateRequest() : RecorderStateRequest(nullptr) {}
  ~RecorderStateRequest() override;
  explicit PROTOBUF_CONSTEXPR RecorderStateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RecorderStateRequest(const RecorderStateRequest& from);
  RecorderStateRequest(RecorderStateRequest&& from) noexcept
    : RecorderStateRequest() {
    *this = ::std::move(from);
  }

  inline RecorderStateRequest& operator=(const RecorderStateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecorderStateRequest& operator=(RecorderStateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecorderStateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecorderStateRequest* internal_default_instance() {
    return reinterpret_cast<const RecorderStateRequest*>(
               &_RecorderStateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RecorderStateRequest& a, RecorderStateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RecorderStateRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecorderStateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecorderStateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecorderStateRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RecorderStateRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RecorderStateRequest& from) {
    RecorderStateRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecorderStateRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.RecorderStateRequest";
  }
  protected:
  explicit RecorderStateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCameraNamesFieldNumber = 1,
  };
  // repeated string camera_names = 1;
  int camera_names_size() const;
  private:
  int _internal_camera_names_size() const;
  public:
  void clear_camera_names();
  const std::string& camera_names(int index) const;
  std::string* mutable_camera_names(int index);
  void set_camera_names(int index, const std::string& value);
  void set_camera_names(int index, std::string&& value);
  void set_camera_names(int index, const char* value);
  void set_camera_names(int index, const char* value, size_t size);
  std::string* add_camera_names();
  void add_camera_names(const std::string& value);
  void add_camera_names(std::string&& value);
  void add_camera_names(const char* value);
  void add_camera_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& camera_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_camera_names();
  private:
  const std::string& _internal_camera_names(int index) const;
  std::string* _internal_add_camera_names();
  public:

  // @@protoc_insertion_point(class_scope:robot.RecorderStateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> camera_names_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// -------------------------------------------------------------------

class RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics) */ {
 public:
  inline RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics() : RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics(nullptr) {}
  ~RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics() override;
  explicit PROTOBUF_CONSTEXPR RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics(const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& from);
  RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics(RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics&& from) noexcept
    : RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics() {
    *this = ::std::move(from);
  }

  inline RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& operator=(const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& operator=(RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* internal_default_instance() {
    return reinterpret_cast<const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics*>(
               &_RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& a, RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& b) {
    a.Swap(&b);
  }
  inline void Swap(RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& from) {
    RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics";
  }
  protected:
  explicit RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCoeffsFieldNumber = 8,
    kModelFieldNumber = 7,
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kFxFieldNumber = 3,
    kFyFieldNumber = 4,
    kPpxFieldNumber = 5,
    kPpyFieldNumber = 6,
  };
  // repeated float coeffs = 8;
  int coeffs_size() const;
  private:
  int _internal_coeffs_size() const;
  public:
  void clear_coeffs();
  private:
  float _internal_coeffs(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_coeffs() const;
  void _internal_add_coeffs(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_coeffs();
  public:
  float coeffs(int index) const;
  void set_coeffs(int index, float value);
  void add_coeffs(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      coeffs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_coeffs();

  // string model = 7;
  void clear_model();
  const std::string& model() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_model(ArgT0&& arg0, ArgT... args);
  std::string* mutable_model();
  PROTOBUF_NODISCARD std::string* release_model();
  void set_allocated_model(std::string* model);
  private:
  const std::string& _internal_model() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_model(const std::string& value);
  std::string* _internal_mutable_model();
  public:

  // uint32 width = 1;
  void clear_width();
  uint32_t width() const;
  void set_width(uint32_t value);
  private:
  uint32_t _internal_width() const;
  void _internal_set_width(uint32_t value);
  public:

  // uint32 height = 2;
  void clear_height();
  uint32_t height() const;
  void set_height(uint32_t value);
  private:
  uint32_t _internal_height() const;
  void _internal_set_height(uint32_t value);
  public:

  // float fx = 3;
  void clear_fx();
  float fx() const;
  void set_fx(float value);
  private:
  float _internal_fx() const;
  void _internal_set_fx(float value);
  public:

  // float fy = 4;
  void clear_fy();
  float fy() const;
  void set_fy(float value);
  private:
  float _internal_fy() const;
  void _internal_set_fy(float value);
  public:

  // float ppx = 5;
  void clear_ppx();
  float ppx() const;
  void set_ppx(float value);
  private:
  float _internal_ppx() const;
  void _internal_set_ppx(float value);
  public:

  // float ppy = 6;
  void clear_ppy();
  float ppy() const;
  void set_ppy(float value);
  private:
  float _internal_ppy() const;
  void _internal_set_ppy(float value);
  public:

  // @@protoc_insertion_point(class_scope:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > coeffs_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_;
    uint32_t width_;
    uint32_t height_;
    float fx_;
    float fy_;
    float ppx_;
    float ppy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// -------------------------------------------------------------------

class RecorderStateResponse_CameraConfig_StreamSpec final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.RecorderStateResponse.CameraConfig.StreamSpec) */ {
 public:
  inline RecorderStateResponse_CameraConfig_StreamSpec() : RecorderStateResponse_CameraConfig_StreamSpec(nullptr) {}
  ~RecorderStateResponse_CameraConfig_StreamSpec() override;
  explicit PROTOBUF_CONSTEXPR RecorderStateResponse_CameraConfig_StreamSpec(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RecorderStateResponse_CameraConfig_StreamSpec(const RecorderStateResponse_CameraConfig_StreamSpec& from);
  RecorderStateResponse_CameraConfig_StreamSpec(RecorderStateResponse_CameraConfig_StreamSpec&& from) noexcept
    : RecorderStateResponse_CameraConfig_StreamSpec() {
    *this = ::std::move(from);
  }

  inline RecorderStateResponse_CameraConfig_StreamSpec& operator=(const RecorderStateResponse_CameraConfig_StreamSpec& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecorderStateResponse_CameraConfig_StreamSpec& operator=(RecorderStateResponse_CameraConfig_StreamSpec&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecorderStateResponse_CameraConfig_StreamSpec& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecorderStateResponse_CameraConfig_StreamSpec* internal_default_instance() {
    return reinterpret_cast<const RecorderStateResponse_CameraConfig_StreamSpec*>(
               &_RecorderStateResponse_CameraConfig_StreamSpec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RecorderStateResponse_CameraConfig_StreamSpec& a, RecorderStateResponse_CameraConfig_StreamSpec& b) {
    a.Swap(&b);
  }
  inline void Swap(RecorderStateResponse_CameraConfig_StreamSpec* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecorderStateResponse_CameraConfig_StreamSpec* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecorderStateResponse_CameraConfig_StreamSpec* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecorderStateResponse_CameraConfig_StreamSpec>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RecorderStateResponse_CameraConfig_StreamSpec& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RecorderStateResponse_CameraConfig_StreamSpec& from) {
    RecorderStateResponse_CameraConfig_StreamSpec::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecorderStateResponse_CameraConfig_StreamSpec* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.RecorderStateResponse.CameraConfig.StreamSpec";
  }
  protected:
  explicit RecorderStateResponse_CameraConfig_StreamSpec(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics RsIntrinsics;

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kIntrinsicsFieldNumber = 5,
    kWidthFieldNumber = 2,
    kHeightFieldNumber = 3,
    kFpsFieldNumber = 4,
  };
  // string type = 1;
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // .robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics intrinsics = 5;
  bool has_intrinsics() const;
  private:
  bool _internal_has_intrinsics() const;
  public:
  void clear_intrinsics();
  const ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& intrinsics() const;
  PROTOBUF_NODISCARD ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* release_intrinsics();
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* mutable_intrinsics();
  void set_allocated_intrinsics(::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* intrinsics);
  private:
  const ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& _internal_intrinsics() const;
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* _internal_mutable_intrinsics();
  public:
  void unsafe_arena_set_allocated_intrinsics(
      ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* intrinsics);
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* unsafe_arena_release_intrinsics();

  // uint32 width = 2;
  void clear_width();
  uint32_t width() const;
  void set_width(uint32_t value);
  private:
  uint32_t _internal_width() const;
  void _internal_set_width(uint32_t value);
  public:

  // uint32 height = 3;
  void clear_height();
  uint32_t height() const;
  void set_height(uint32_t value);
  private:
  uint32_t _internal_height() const;
  void _internal_set_height(uint32_t value);
  public:

  // uint32 fps = 4;
  void clear_fps();
  uint32_t fps() const;
  void set_fps(uint32_t value);
  private:
  uint32_t _internal_fps() const;
  void _internal_set_fps(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:robot.RecorderStateResponse.CameraConfig.StreamSpec)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* intrinsics_;
    uint32_t width_;
    uint32_t height_;
    uint32_t fps_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// -------------------------------------------------------------------

class RecorderStateResponse_CameraConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.RecorderStateResponse.CameraConfig) */ {
 public:
  inline RecorderStateResponse_CameraConfig() : RecorderStateResponse_CameraConfig(nullptr) {}
  ~RecorderStateResponse_CameraConfig() override;
  explicit PROTOBUF_CONSTEXPR RecorderStateResponse_CameraConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RecorderStateResponse_CameraConfig(const RecorderStateResponse_CameraConfig& from);
  RecorderStateResponse_CameraConfig(RecorderStateResponse_CameraConfig&& from) noexcept
    : RecorderStateResponse_CameraConfig() {
    *this = ::std::move(from);
  }

  inline RecorderStateResponse_CameraConfig& operator=(const RecorderStateResponse_CameraConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecorderStateResponse_CameraConfig& operator=(RecorderStateResponse_CameraConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecorderStateResponse_CameraConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecorderStateResponse_CameraConfig* internal_default_instance() {
    return reinterpret_cast<const RecorderStateResponse_CameraConfig*>(
               &_RecorderStateResponse_CameraConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(RecorderStateResponse_CameraConfig& a, RecorderStateResponse_CameraConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(RecorderStateResponse_CameraConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecorderStateResponse_CameraConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecorderStateResponse_CameraConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecorderStateResponse_CameraConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RecorderStateResponse_CameraConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RecorderStateResponse_CameraConfig& from) {
    RecorderStateResponse_CameraConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecorderStateResponse_CameraConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.RecorderStateResponse.CameraConfig";
  }
  protected:
  explicit RecorderStateResponse_CameraConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef RecorderStateResponse_CameraConfig_StreamSpec StreamSpec;

  // accessors -------------------------------------------------------

  enum : int {
    kStreamsFieldNumber = 2,
    kCameraNameFieldNumber = 1,
  };
  // repeated .robot.RecorderStateResponse.CameraConfig.StreamSpec streams = 2;
  int streams_size() const;
  private:
  int _internal_streams_size() const;
  public:
  void clear_streams();
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec* mutable_streams(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig_StreamSpec >*
      mutable_streams();
  private:
  const ::robot::RecorderStateResponse_CameraConfig_StreamSpec& _internal_streams(int index) const;
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec* _internal_add_streams();
  public:
  const ::robot::RecorderStateResponse_CameraConfig_StreamSpec& streams(int index) const;
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec* add_streams();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig_StreamSpec >&
      streams() const;

  // string camera_name = 1;
  void clear_camera_name();
  const std::string& camera_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_camera_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_camera_name();
  PROTOBUF_NODISCARD std::string* release_camera_name();
  void set_allocated_camera_name(std::string* camera_name);
  private:
  const std::string& _internal_camera_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_camera_name(const std::string& value);
  std::string* _internal_mutable_camera_name();
  public:

  // @@protoc_insertion_point(class_scope:robot.RecorderStateResponse.CameraConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig_StreamSpec > streams_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camera_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// -------------------------------------------------------------------

class RecorderStateResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:robot.RecorderStateResponse) */ {
 public:
  inline RecorderStateResponse() : RecorderStateResponse(nullptr) {}
  ~RecorderStateResponse() override;
  explicit PROTOBUF_CONSTEXPR RecorderStateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RecorderStateResponse(const RecorderStateResponse& from);
  RecorderStateResponse(RecorderStateResponse&& from) noexcept
    : RecorderStateResponse() {
    *this = ::std::move(from);
  }

  inline RecorderStateResponse& operator=(const RecorderStateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecorderStateResponse& operator=(RecorderStateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RecorderStateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const RecorderStateResponse* internal_default_instance() {
    return reinterpret_cast<const RecorderStateResponse*>(
               &_RecorderStateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(RecorderStateResponse& a, RecorderStateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(RecorderStateResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecorderStateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RecorderStateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RecorderStateResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RecorderStateResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RecorderStateResponse& from) {
    RecorderStateResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecorderStateResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "robot.RecorderStateResponse";
  }
  protected:
  explicit RecorderStateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef RecorderStateResponse_CameraConfig CameraConfig;

  // accessors -------------------------------------------------------

  enum : int {
    kCameraConfigsFieldNumber = 1,
  };
  // repeated .robot.RecorderStateResponse.CameraConfig camera_configs = 1;
  int camera_configs_size() const;
  private:
  int _internal_camera_configs_size() const;
  public:
  void clear_camera_configs();
  ::robot::RecorderStateResponse_CameraConfig* mutable_camera_configs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig >*
      mutable_camera_configs();
  private:
  const ::robot::RecorderStateResponse_CameraConfig& _internal_camera_configs(int index) const;
  ::robot::RecorderStateResponse_CameraConfig* _internal_add_camera_configs();
  public:
  const ::robot::RecorderStateResponse_CameraConfig& camera_configs(int index) const;
  ::robot::RecorderStateResponse_CameraConfig* add_camera_configs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig >&
      camera_configs() const;

  // @@protoc_insertion_point(class_scope:robot.RecorderStateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig > camera_configs_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_robot_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ControlSignalRequest

// .robot.ControlSignalRequest.ActionType action = 1;
inline void ControlSignalRequest::clear_action() {
  _impl_.action_ = 0;
}
inline ::robot::ControlSignalRequest_ActionType ControlSignalRequest::_internal_action() const {
  return static_cast< ::robot::ControlSignalRequest_ActionType >(_impl_.action_);
}
inline ::robot::ControlSignalRequest_ActionType ControlSignalRequest::action() const {
  // @@protoc_insertion_point(field_get:robot.ControlSignalRequest.action)
  return _internal_action();
}
inline void ControlSignalRequest::_internal_set_action(::robot::ControlSignalRequest_ActionType value) {
  
  _impl_.action_ = value;
}
inline void ControlSignalRequest::set_action(::robot::ControlSignalRequest_ActionType value) {
  _internal_set_action(value);
  // @@protoc_insertion_point(field_set:robot.ControlSignalRequest.action)
}

// string sdp_type = 2;
inline void ControlSignalRequest::clear_sdp_type() {
  _impl_.sdp_type_.ClearToEmpty();
}
inline const std::string& ControlSignalRequest::sdp_type() const {
  // @@protoc_insertion_point(field_get:robot.ControlSignalRequest.sdp_type)
  return _internal_sdp_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ControlSignalRequest::set_sdp_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sdp_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.ControlSignalRequest.sdp_type)
}
inline std::string* ControlSignalRequest::mutable_sdp_type() {
  std::string* _s = _internal_mutable_sdp_type();
  // @@protoc_insertion_point(field_mutable:robot.ControlSignalRequest.sdp_type)
  return _s;
}
inline const std::string& ControlSignalRequest::_internal_sdp_type() const {
  return _impl_.sdp_type_.Get();
}
inline void ControlSignalRequest::_internal_set_sdp_type(const std::string& value) {
  
  _impl_.sdp_type_.Set(value, GetArenaForAllocation());
}
inline std::string* ControlSignalRequest::_internal_mutable_sdp_type() {
  
  return _impl_.sdp_type_.Mutable(GetArenaForAllocation());
}
inline std::string* ControlSignalRequest::release_sdp_type() {
  // @@protoc_insertion_point(field_release:robot.ControlSignalRequest.sdp_type)
  return _impl_.sdp_type_.Release();
}
inline void ControlSignalRequest::set_allocated_sdp_type(std::string* sdp_type) {
  if (sdp_type != nullptr) {
    
  } else {
    
  }
  _impl_.sdp_type_.SetAllocated(sdp_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sdp_type_.IsDefault()) {
    _impl_.sdp_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.ControlSignalRequest.sdp_type)
}

// string sdp = 3;
inline void ControlSignalRequest::clear_sdp() {
  _impl_.sdp_.ClearToEmpty();
}
inline const std::string& ControlSignalRequest::sdp() const {
  // @@protoc_insertion_point(field_get:robot.ControlSignalRequest.sdp)
  return _internal_sdp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ControlSignalRequest::set_sdp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sdp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.ControlSignalRequest.sdp)
}
inline std::string* ControlSignalRequest::mutable_sdp() {
  std::string* _s = _internal_mutable_sdp();
  // @@protoc_insertion_point(field_mutable:robot.ControlSignalRequest.sdp)
  return _s;
}
inline const std::string& ControlSignalRequest::_internal_sdp() const {
  return _impl_.sdp_.Get();
}
inline void ControlSignalRequest::_internal_set_sdp(const std::string& value) {
  
  _impl_.sdp_.Set(value, GetArenaForAllocation());
}
inline std::string* ControlSignalRequest::_internal_mutable_sdp() {
  
  return _impl_.sdp_.Mutable(GetArenaForAllocation());
}
inline std::string* ControlSignalRequest::release_sdp() {
  // @@protoc_insertion_point(field_release:robot.ControlSignalRequest.sdp)
  return _impl_.sdp_.Release();
}
inline void ControlSignalRequest::set_allocated_sdp(std::string* sdp) {
  if (sdp != nullptr) {
    
  } else {
    
  }
  _impl_.sdp_.SetAllocated(sdp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sdp_.IsDefault()) {
    _impl_.sdp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.ControlSignalRequest.sdp)
}

// -------------------------------------------------------------------

// ControlSignalResponse

// string status = 1;
inline void ControlSignalResponse::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& ControlSignalResponse::status() const {
  // @@protoc_insertion_point(field_get:robot.ControlSignalResponse.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ControlSignalResponse::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.ControlSignalResponse.status)
}
inline std::string* ControlSignalResponse::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:robot.ControlSignalResponse.status)
  return _s;
}
inline const std::string& ControlSignalResponse::_internal_status() const {
  return _impl_.status_.Get();
}
inline void ControlSignalResponse::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* ControlSignalResponse::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* ControlSignalResponse::release_status() {
  // @@protoc_insertion_point(field_release:robot.ControlSignalResponse.status)
  return _impl_.status_.Release();
}
inline void ControlSignalResponse::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.ControlSignalResponse.status)
}

// string sdp_type = 2;
inline void ControlSignalResponse::clear_sdp_type() {
  _impl_.sdp_type_.ClearToEmpty();
}
inline const std::string& ControlSignalResponse::sdp_type() const {
  // @@protoc_insertion_point(field_get:robot.ControlSignalResponse.sdp_type)
  return _internal_sdp_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ControlSignalResponse::set_sdp_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sdp_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.ControlSignalResponse.sdp_type)
}
inline std::string* ControlSignalResponse::mutable_sdp_type() {
  std::string* _s = _internal_mutable_sdp_type();
  // @@protoc_insertion_point(field_mutable:robot.ControlSignalResponse.sdp_type)
  return _s;
}
inline const std::string& ControlSignalResponse::_internal_sdp_type() const {
  return _impl_.sdp_type_.Get();
}
inline void ControlSignalResponse::_internal_set_sdp_type(const std::string& value) {
  
  _impl_.sdp_type_.Set(value, GetArenaForAllocation());
}
inline std::string* ControlSignalResponse::_internal_mutable_sdp_type() {
  
  return _impl_.sdp_type_.Mutable(GetArenaForAllocation());
}
inline std::string* ControlSignalResponse::release_sdp_type() {
  // @@protoc_insertion_point(field_release:robot.ControlSignalResponse.sdp_type)
  return _impl_.sdp_type_.Release();
}
inline void ControlSignalResponse::set_allocated_sdp_type(std::string* sdp_type) {
  if (sdp_type != nullptr) {
    
  } else {
    
  }
  _impl_.sdp_type_.SetAllocated(sdp_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sdp_type_.IsDefault()) {
    _impl_.sdp_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.ControlSignalResponse.sdp_type)
}

// string sdp = 3;
inline void ControlSignalResponse::clear_sdp() {
  _impl_.sdp_.ClearToEmpty();
}
inline const std::string& ControlSignalResponse::sdp() const {
  // @@protoc_insertion_point(field_get:robot.ControlSignalResponse.sdp)
  return _internal_sdp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ControlSignalResponse::set_sdp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sdp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.ControlSignalResponse.sdp)
}
inline std::string* ControlSignalResponse::mutable_sdp() {
  std::string* _s = _internal_mutable_sdp();
  // @@protoc_insertion_point(field_mutable:robot.ControlSignalResponse.sdp)
  return _s;
}
inline const std::string& ControlSignalResponse::_internal_sdp() const {
  return _impl_.sdp_.Get();
}
inline void ControlSignalResponse::_internal_set_sdp(const std::string& value) {
  
  _impl_.sdp_.Set(value, GetArenaForAllocation());
}
inline std::string* ControlSignalResponse::_internal_mutable_sdp() {
  
  return _impl_.sdp_.Mutable(GetArenaForAllocation());
}
inline std::string* ControlSignalResponse::release_sdp() {
  // @@protoc_insertion_point(field_release:robot.ControlSignalResponse.sdp)
  return _impl_.sdp_.Release();
}
inline void ControlSignalResponse::set_allocated_sdp(std::string* sdp) {
  if (sdp != nullptr) {
    
  } else {
    
  }
  _impl_.sdp_.SetAllocated(sdp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sdp_.IsDefault()) {
    _impl_.sdp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.ControlSignalResponse.sdp)
}

// -------------------------------------------------------------------

// RecorderStateRequest

// repeated string camera_names = 1;
inline int RecorderStateRequest::_internal_camera_names_size() const {
  return _impl_.camera_names_.size();
}
inline int RecorderStateRequest::camera_names_size() const {
  return _internal_camera_names_size();
}
inline void RecorderStateRequest::clear_camera_names() {
  _impl_.camera_names_.Clear();
}
inline std::string* RecorderStateRequest::add_camera_names() {
  std::string* _s = _internal_add_camera_names();
  // @@protoc_insertion_point(field_add_mutable:robot.RecorderStateRequest.camera_names)
  return _s;
}
inline const std::string& RecorderStateRequest::_internal_camera_names(int index) const {
  return _impl_.camera_names_.Get(index);
}
inline const std::string& RecorderStateRequest::camera_names(int index) const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateRequest.camera_names)
  return _internal_camera_names(index);
}
inline std::string* RecorderStateRequest::mutable_camera_names(int index) {
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateRequest.camera_names)
  return _impl_.camera_names_.Mutable(index);
}
inline void RecorderStateRequest::set_camera_names(int index, const std::string& value) {
  _impl_.camera_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateRequest.camera_names)
}
inline void RecorderStateRequest::set_camera_names(int index, std::string&& value) {
  _impl_.camera_names_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:robot.RecorderStateRequest.camera_names)
}
inline void RecorderStateRequest::set_camera_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.camera_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:robot.RecorderStateRequest.camera_names)
}
inline void RecorderStateRequest::set_camera_names(int index, const char* value, size_t size) {
  _impl_.camera_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:robot.RecorderStateRequest.camera_names)
}
inline std::string* RecorderStateRequest::_internal_add_camera_names() {
  return _impl_.camera_names_.Add();
}
inline void RecorderStateRequest::add_camera_names(const std::string& value) {
  _impl_.camera_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:robot.RecorderStateRequest.camera_names)
}
inline void RecorderStateRequest::add_camera_names(std::string&& value) {
  _impl_.camera_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:robot.RecorderStateRequest.camera_names)
}
inline void RecorderStateRequest::add_camera_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.camera_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:robot.RecorderStateRequest.camera_names)
}
inline void RecorderStateRequest::add_camera_names(const char* value, size_t size) {
  _impl_.camera_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:robot.RecorderStateRequest.camera_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
RecorderStateRequest::camera_names() const {
  // @@protoc_insertion_point(field_list:robot.RecorderStateRequest.camera_names)
  return _impl_.camera_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
RecorderStateRequest::mutable_camera_names() {
  // @@protoc_insertion_point(field_mutable_list:robot.RecorderStateRequest.camera_names)
  return &_impl_.camera_names_;
}

// -------------------------------------------------------------------

// RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics

// uint32 width = 1;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_width() {
  _impl_.width_ = 0u;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_width() const {
  return _impl_.width_;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::width() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.width)
  return _internal_width();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_width(uint32_t value) {
  
  _impl_.width_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_width(uint32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.width)
}

// uint32 height = 2;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_height() {
  _impl_.height_ = 0u;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_height() const {
  return _impl_.height_;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::height() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.height)
  return _internal_height();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_height(uint32_t value) {
  
  _impl_.height_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_height(uint32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.height)
}

// float fx = 3;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_fx() {
  _impl_.fx_ = 0;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_fx() const {
  return _impl_.fx_;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::fx() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.fx)
  return _internal_fx();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_fx(float value) {
  
  _impl_.fx_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_fx(float value) {
  _internal_set_fx(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.fx)
}

// float fy = 4;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_fy() {
  _impl_.fy_ = 0;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_fy() const {
  return _impl_.fy_;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::fy() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.fy)
  return _internal_fy();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_fy(float value) {
  
  _impl_.fy_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_fy(float value) {
  _internal_set_fy(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.fy)
}

// float ppx = 5;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_ppx() {
  _impl_.ppx_ = 0;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_ppx() const {
  return _impl_.ppx_;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::ppx() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.ppx)
  return _internal_ppx();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_ppx(float value) {
  
  _impl_.ppx_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_ppx(float value) {
  _internal_set_ppx(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.ppx)
}

// float ppy = 6;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_ppy() {
  _impl_.ppy_ = 0;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_ppy() const {
  return _impl_.ppy_;
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::ppy() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.ppy)
  return _internal_ppy();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_ppy(float value) {
  
  _impl_.ppy_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_ppy(float value) {
  _internal_set_ppy(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.ppy)
}

// string model = 7;
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_model() {
  _impl_.model_.ClearToEmpty();
}
inline const std::string& RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::model() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.model)
  return _internal_model();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_model(ArgT0&& arg0, ArgT... args) {
 
 _impl_.model_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.model)
}
inline std::string* RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::mutable_model() {
  std::string* _s = _internal_mutable_model();
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.model)
  return _s;
}
inline const std::string& RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_model() const {
  return _impl_.model_.Get();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_set_model(const std::string& value) {
  
  _impl_.model_.Set(value, GetArenaForAllocation());
}
inline std::string* RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_mutable_model() {
  
  return _impl_.model_.Mutable(GetArenaForAllocation());
}
inline std::string* RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::release_model() {
  // @@protoc_insertion_point(field_release:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.model)
  return _impl_.model_.Release();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_allocated_model(std::string* model) {
  if (model != nullptr) {
    
  } else {
    
  }
  _impl_.model_.SetAllocated(model, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.model_.IsDefault()) {
    _impl_.model_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.model)
}

// repeated float coeffs = 8;
inline int RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_coeffs_size() const {
  return _impl_.coeffs_.size();
}
inline int RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::coeffs_size() const {
  return _internal_coeffs_size();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::clear_coeffs() {
  _impl_.coeffs_.Clear();
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_coeffs(int index) const {
  return _impl_.coeffs_.Get(index);
}
inline float RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::coeffs(int index) const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.coeffs)
  return _internal_coeffs(index);
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::set_coeffs(int index, float value) {
  _impl_.coeffs_.Set(index, value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.coeffs)
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_add_coeffs(float value) {
  _impl_.coeffs_.Add(value);
}
inline void RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::add_coeffs(float value) {
  _internal_add_coeffs(value);
  // @@protoc_insertion_point(field_add:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.coeffs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_coeffs() const {
  return _impl_.coeffs_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::coeffs() const {
  // @@protoc_insertion_point(field_list:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.coeffs)
  return _internal_coeffs();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::_internal_mutable_coeffs() {
  return &_impl_.coeffs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics::mutable_coeffs() {
  // @@protoc_insertion_point(field_mutable_list:robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics.coeffs)
  return _internal_mutable_coeffs();
}

// -------------------------------------------------------------------

// RecorderStateResponse_CameraConfig_StreamSpec

// string type = 1;
inline void RecorderStateResponse_CameraConfig_StreamSpec::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& RecorderStateResponse_CameraConfig_StreamSpec::type() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RecorderStateResponse_CameraConfig_StreamSpec::set_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.type)
}
inline std::string* RecorderStateResponse_CameraConfig_StreamSpec::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateResponse.CameraConfig.StreamSpec.type)
  return _s;
}
inline const std::string& RecorderStateResponse_CameraConfig_StreamSpec::_internal_type() const {
  return _impl_.type_.Get();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::_internal_set_type(const std::string& value) {
  
  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* RecorderStateResponse_CameraConfig_StreamSpec::_internal_mutable_type() {
  
  return _impl_.type_.Mutable(GetArenaForAllocation());
}
inline std::string* RecorderStateResponse_CameraConfig_StreamSpec::release_type() {
  // @@protoc_insertion_point(field_release:robot.RecorderStateResponse.CameraConfig.StreamSpec.type)
  return _impl_.type_.Release();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  _impl_.type_.SetAllocated(type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.RecorderStateResponse.CameraConfig.StreamSpec.type)
}

// uint32 width = 2;
inline void RecorderStateResponse_CameraConfig_StreamSpec::clear_width() {
  _impl_.width_ = 0u;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec::_internal_width() const {
  return _impl_.width_;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec::width() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.width)
  return _internal_width();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::_internal_set_width(uint32_t value) {
  
  _impl_.width_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::set_width(uint32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.width)
}

// uint32 height = 3;
inline void RecorderStateResponse_CameraConfig_StreamSpec::clear_height() {
  _impl_.height_ = 0u;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec::_internal_height() const {
  return _impl_.height_;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec::height() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.height)
  return _internal_height();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::_internal_set_height(uint32_t value) {
  
  _impl_.height_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::set_height(uint32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.height)
}

// uint32 fps = 4;
inline void RecorderStateResponse_CameraConfig_StreamSpec::clear_fps() {
  _impl_.fps_ = 0u;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec::_internal_fps() const {
  return _impl_.fps_;
}
inline uint32_t RecorderStateResponse_CameraConfig_StreamSpec::fps() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.fps)
  return _internal_fps();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::_internal_set_fps(uint32_t value) {
  
  _impl_.fps_ = value;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::set_fps(uint32_t value) {
  _internal_set_fps(value);
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.StreamSpec.fps)
}

// .robot.RecorderStateResponse.CameraConfig.StreamSpec.RsIntrinsics intrinsics = 5;
inline bool RecorderStateResponse_CameraConfig_StreamSpec::_internal_has_intrinsics() const {
  return this != internal_default_instance() && _impl_.intrinsics_ != nullptr;
}
inline bool RecorderStateResponse_CameraConfig_StreamSpec::has_intrinsics() const {
  return _internal_has_intrinsics();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::clear_intrinsics() {
  if (GetArenaForAllocation() == nullptr && _impl_.intrinsics_ != nullptr) {
    delete _impl_.intrinsics_;
  }
  _impl_.intrinsics_ = nullptr;
}
inline const ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& RecorderStateResponse_CameraConfig_StreamSpec::_internal_intrinsics() const {
  const ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* p = _impl_.intrinsics_;
  return p != nullptr ? *p : reinterpret_cast<const ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics&>(
      ::robot::_RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics_default_instance_);
}
inline const ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics& RecorderStateResponse_CameraConfig_StreamSpec::intrinsics() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.StreamSpec.intrinsics)
  return _internal_intrinsics();
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::unsafe_arena_set_allocated_intrinsics(
    ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* intrinsics) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.intrinsics_);
  }
  _impl_.intrinsics_ = intrinsics;
  if (intrinsics) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:robot.RecorderStateResponse.CameraConfig.StreamSpec.intrinsics)
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* RecorderStateResponse_CameraConfig_StreamSpec::release_intrinsics() {
  
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* temp = _impl_.intrinsics_;
  _impl_.intrinsics_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* RecorderStateResponse_CameraConfig_StreamSpec::unsafe_arena_release_intrinsics() {
  // @@protoc_insertion_point(field_release:robot.RecorderStateResponse.CameraConfig.StreamSpec.intrinsics)
  
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* temp = _impl_.intrinsics_;
  _impl_.intrinsics_ = nullptr;
  return temp;
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* RecorderStateResponse_CameraConfig_StreamSpec::_internal_mutable_intrinsics() {
  
  if (_impl_.intrinsics_ == nullptr) {
    auto* p = CreateMaybeMessage<::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics>(GetArenaForAllocation());
    _impl_.intrinsics_ = p;
  }
  return _impl_.intrinsics_;
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* RecorderStateResponse_CameraConfig_StreamSpec::mutable_intrinsics() {
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* _msg = _internal_mutable_intrinsics();
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateResponse.CameraConfig.StreamSpec.intrinsics)
  return _msg;
}
inline void RecorderStateResponse_CameraConfig_StreamSpec::set_allocated_intrinsics(::robot::RecorderStateResponse_CameraConfig_StreamSpec_RsIntrinsics* intrinsics) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.intrinsics_;
  }
  if (intrinsics) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(intrinsics);
    if (message_arena != submessage_arena) {
      intrinsics = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, intrinsics, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.intrinsics_ = intrinsics;
  // @@protoc_insertion_point(field_set_allocated:robot.RecorderStateResponse.CameraConfig.StreamSpec.intrinsics)
}

// -------------------------------------------------------------------

// RecorderStateResponse_CameraConfig

// string camera_name = 1;
inline void RecorderStateResponse_CameraConfig::clear_camera_name() {
  _impl_.camera_name_.ClearToEmpty();
}
inline const std::string& RecorderStateResponse_CameraConfig::camera_name() const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.camera_name)
  return _internal_camera_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RecorderStateResponse_CameraConfig::set_camera_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.camera_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:robot.RecorderStateResponse.CameraConfig.camera_name)
}
inline std::string* RecorderStateResponse_CameraConfig::mutable_camera_name() {
  std::string* _s = _internal_mutable_camera_name();
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateResponse.CameraConfig.camera_name)
  return _s;
}
inline const std::string& RecorderStateResponse_CameraConfig::_internal_camera_name() const {
  return _impl_.camera_name_.Get();
}
inline void RecorderStateResponse_CameraConfig::_internal_set_camera_name(const std::string& value) {
  
  _impl_.camera_name_.Set(value, GetArenaForAllocation());
}
inline std::string* RecorderStateResponse_CameraConfig::_internal_mutable_camera_name() {
  
  return _impl_.camera_name_.Mutable(GetArenaForAllocation());
}
inline std::string* RecorderStateResponse_CameraConfig::release_camera_name() {
  // @@protoc_insertion_point(field_release:robot.RecorderStateResponse.CameraConfig.camera_name)
  return _impl_.camera_name_.Release();
}
inline void RecorderStateResponse_CameraConfig::set_allocated_camera_name(std::string* camera_name) {
  if (camera_name != nullptr) {
    
  } else {
    
  }
  _impl_.camera_name_.SetAllocated(camera_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.camera_name_.IsDefault()) {
    _impl_.camera_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:robot.RecorderStateResponse.CameraConfig.camera_name)
}

// repeated .robot.RecorderStateResponse.CameraConfig.StreamSpec streams = 2;
inline int RecorderStateResponse_CameraConfig::_internal_streams_size() const {
  return _impl_.streams_.size();
}
inline int RecorderStateResponse_CameraConfig::streams_size() const {
  return _internal_streams_size();
}
inline void RecorderStateResponse_CameraConfig::clear_streams() {
  _impl_.streams_.Clear();
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec* RecorderStateResponse_CameraConfig::mutable_streams(int index) {
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateResponse.CameraConfig.streams)
  return _impl_.streams_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig_StreamSpec >*
RecorderStateResponse_CameraConfig::mutable_streams() {
  // @@protoc_insertion_point(field_mutable_list:robot.RecorderStateResponse.CameraConfig.streams)
  return &_impl_.streams_;
}
inline const ::robot::RecorderStateResponse_CameraConfig_StreamSpec& RecorderStateResponse_CameraConfig::_internal_streams(int index) const {
  return _impl_.streams_.Get(index);
}
inline const ::robot::RecorderStateResponse_CameraConfig_StreamSpec& RecorderStateResponse_CameraConfig::streams(int index) const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.CameraConfig.streams)
  return _internal_streams(index);
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec* RecorderStateResponse_CameraConfig::_internal_add_streams() {
  return _impl_.streams_.Add();
}
inline ::robot::RecorderStateResponse_CameraConfig_StreamSpec* RecorderStateResponse_CameraConfig::add_streams() {
  ::robot::RecorderStateResponse_CameraConfig_StreamSpec* _add = _internal_add_streams();
  // @@protoc_insertion_point(field_add:robot.RecorderStateResponse.CameraConfig.streams)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig_StreamSpec >&
RecorderStateResponse_CameraConfig::streams() const {
  // @@protoc_insertion_point(field_list:robot.RecorderStateResponse.CameraConfig.streams)
  return _impl_.streams_;
}

// -------------------------------------------------------------------

// RecorderStateResponse

// repeated .robot.RecorderStateResponse.CameraConfig camera_configs = 1;
inline int RecorderStateResponse::_internal_camera_configs_size() const {
  return _impl_.camera_configs_.size();
}
inline int RecorderStateResponse::camera_configs_size() const {
  return _internal_camera_configs_size();
}
inline void RecorderStateResponse::clear_camera_configs() {
  _impl_.camera_configs_.Clear();
}
inline ::robot::RecorderStateResponse_CameraConfig* RecorderStateResponse::mutable_camera_configs(int index) {
  // @@protoc_insertion_point(field_mutable:robot.RecorderStateResponse.camera_configs)
  return _impl_.camera_configs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig >*
RecorderStateResponse::mutable_camera_configs() {
  // @@protoc_insertion_point(field_mutable_list:robot.RecorderStateResponse.camera_configs)
  return &_impl_.camera_configs_;
}
inline const ::robot::RecorderStateResponse_CameraConfig& RecorderStateResponse::_internal_camera_configs(int index) const {
  return _impl_.camera_configs_.Get(index);
}
inline const ::robot::RecorderStateResponse_CameraConfig& RecorderStateResponse::camera_configs(int index) const {
  // @@protoc_insertion_point(field_get:robot.RecorderStateResponse.camera_configs)
  return _internal_camera_configs(index);
}
inline ::robot::RecorderStateResponse_CameraConfig* RecorderStateResponse::_internal_add_camera_configs() {
  return _impl_.camera_configs_.Add();
}
inline ::robot::RecorderStateResponse_CameraConfig* RecorderStateResponse::add_camera_configs() {
  ::robot::RecorderStateResponse_CameraConfig* _add = _internal_add_camera_configs();
  // @@protoc_insertion_point(field_add:robot.RecorderStateResponse.camera_configs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::robot::RecorderStateResponse_CameraConfig >&
RecorderStateResponse::camera_configs() const {
  // @@protoc_insertion_point(field_list:robot.RecorderStateResponse.camera_configs)
  return _impl_.camera_configs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace robot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::robot::ControlSignalRequest_ActionType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::robot::ControlSignalRequest_ActionType>() {
  return ::robot::ControlSignalRequest_ActionType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_robot_2eproto
