// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: robot.proto
#ifndef GRPC_robot_2eproto__INCLUDED
#define GRPC_robot_2eproto__INCLUDED

#include "robot.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace robot {

// *
// 统一服务（无 CameraBackend 枚举；仅用 oneof 选择 RS / V4L2）
class RobotService final {
 public:
  static constexpr char const* service_full_name() {
    return "robot.RobotService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::robot::ControlSignalResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>> AsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>>(AsyncControlVideoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>> PrepareAsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>>(PrepareAsyncControlVideoRaw(context, request, cq));
    }
    virtual ::grpc::Status RecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::robot::RecorderReinitReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderReinitReply>> AsyncRecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderReinitReply>>(AsyncRecorderReinitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderReinitReply>> PrepareAsyncRecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderReinitReply>>(PrepareAsyncRecorderReinitRaw(context, request, cq));
    }
    virtual ::grpc::Status RecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::robot::RecorderGetStateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderGetStateReply>> AsyncRecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderGetStateReply>>(AsyncRecorderGetStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderGetStateReply>> PrepareAsyncRecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderGetStateReply>>(PrepareAsyncRecorderGetStateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest* request, ::robot::RecorderReinitReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest* request, ::robot::RecorderReinitReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest* request, ::robot::RecorderGetStateReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest* request, ::robot::RecorderGetStateReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>* AsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>* PrepareAsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderReinitReply>* AsyncRecorderReinitRaw(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderReinitReply>* PrepareAsyncRecorderReinitRaw(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderGetStateReply>* AsyncRecorderGetStateRaw(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderGetStateReply>* PrepareAsyncRecorderGetStateRaw(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::robot::ControlSignalResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>> AsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>>(AsyncControlVideoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>> PrepareAsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>>(PrepareAsyncControlVideoRaw(context, request, cq));
    }
    ::grpc::Status RecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::robot::RecorderReinitReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderReinitReply>> AsyncRecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderReinitReply>>(AsyncRecorderReinitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderReinitReply>> PrepareAsyncRecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderReinitReply>>(PrepareAsyncRecorderReinitRaw(context, request, cq));
    }
    ::grpc::Status RecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::robot::RecorderGetStateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderGetStateReply>> AsyncRecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderGetStateReply>>(AsyncRecorderGetStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderGetStateReply>> PrepareAsyncRecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderGetStateReply>>(PrepareAsyncRecorderGetStateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, std::function<void(::grpc::Status)>) override;
      void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest* request, ::robot::RecorderReinitReply* response, std::function<void(::grpc::Status)>) override;
      void RecorderReinit(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest* request, ::robot::RecorderReinitReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest* request, ::robot::RecorderGetStateReply* response, std::function<void(::grpc::Status)>) override;
      void RecorderGetState(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest* request, ::robot::RecorderGetStateReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>* AsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>* PrepareAsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::RecorderReinitReply>* AsyncRecorderReinitRaw(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::RecorderReinitReply>* PrepareAsyncRecorderReinitRaw(::grpc::ClientContext* context, const ::robot::RecorderReinitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::RecorderGetStateReply>* AsyncRecorderGetStateRaw(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::RecorderGetStateReply>* PrepareAsyncRecorderGetStateRaw(::grpc::ClientContext* context, const ::robot::RecorderGetStateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ControlVideo_;
    const ::grpc::internal::RpcMethod rpcmethod_RecorderReinit_;
    const ::grpc::internal::RpcMethod rpcmethod_RecorderGetState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ControlVideo(::grpc::ServerContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response);
    virtual ::grpc::Status RecorderReinit(::grpc::ServerContext* context, const ::robot::RecorderReinitRequest* request, ::robot::RecorderReinitReply* response);
    virtual ::grpc::Status RecorderGetState(::grpc::ServerContext* context, const ::robot::RecorderGetStateRequest* request, ::robot::RecorderGetStateReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ControlVideo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControlVideo(::grpc::ServerContext* context, ::robot::ControlSignalRequest* request, ::grpc::ServerAsyncResponseWriter< ::robot::ControlSignalResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RecorderReinit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecorderReinit() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RecorderReinit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderReinit(::grpc::ServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecorderReinit(::grpc::ServerContext* context, ::robot::RecorderReinitRequest* request, ::grpc::ServerAsyncResponseWriter< ::robot::RecorderReinitReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RecorderGetState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecorderGetState() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RecorderGetState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderGetState(::grpc::ServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecorderGetState(::grpc::ServerContext* context, ::robot::RecorderGetStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::robot::RecorderGetStateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ControlVideo<WithAsyncMethod_RecorderReinit<WithAsyncMethod_RecorderGetState<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ControlVideo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response) { return this->ControlVideo(context, request, response); }));}
    void SetMessageAllocatorFor_ControlVideo(
        ::grpc::MessageAllocator< ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ControlVideo(
      ::grpc::CallbackServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RecorderReinit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RecorderReinit() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::robot::RecorderReinitRequest, ::robot::RecorderReinitReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::robot::RecorderReinitRequest* request, ::robot::RecorderReinitReply* response) { return this->RecorderReinit(context, request, response); }));}
    void SetMessageAllocatorFor_RecorderReinit(
        ::grpc::MessageAllocator< ::robot::RecorderReinitRequest, ::robot::RecorderReinitReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::robot::RecorderReinitRequest, ::robot::RecorderReinitReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RecorderReinit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderReinit(::grpc::ServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecorderReinit(
      ::grpc::CallbackServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RecorderGetState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RecorderGetState() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::robot::RecorderGetStateRequest, ::robot::RecorderGetStateReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::robot::RecorderGetStateRequest* request, ::robot::RecorderGetStateReply* response) { return this->RecorderGetState(context, request, response); }));}
    void SetMessageAllocatorFor_RecorderGetState(
        ::grpc::MessageAllocator< ::robot::RecorderGetStateRequest, ::robot::RecorderGetStateReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::robot::RecorderGetStateRequest, ::robot::RecorderGetStateReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RecorderGetState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderGetState(::grpc::ServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecorderGetState(
      ::grpc::CallbackServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ControlVideo<WithCallbackMethod_RecorderReinit<WithCallbackMethod_RecorderGetState<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ControlVideo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RecorderReinit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecorderReinit() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RecorderReinit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderReinit(::grpc::ServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RecorderGetState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecorderGetState() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RecorderGetState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderGetState(::grpc::ServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ControlVideo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControlVideo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecorderReinit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecorderReinit() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RecorderReinit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderReinit(::grpc::ServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecorderReinit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecorderGetState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecorderGetState() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RecorderGetState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderGetState(::grpc::ServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecorderGetState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ControlVideo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ControlVideo(context, request, response); }));
    }
    ~WithRawCallbackMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ControlVideo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RecorderReinit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RecorderReinit() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecorderReinit(context, request, response); }));
    }
    ~WithRawCallbackMethod_RecorderReinit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderReinit(::grpc::ServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecorderReinit(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RecorderGetState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RecorderGetState() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecorderGetState(context, request, response); }));
    }
    ~WithRawCallbackMethod_RecorderGetState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecorderGetState(::grpc::ServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecorderGetState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ControlVideo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>* streamer) {
                       return this->StreamedControlVideo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedControlVideo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::robot::ControlSignalRequest,::robot::ControlSignalResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecorderReinit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecorderReinit() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::robot::RecorderReinitRequest, ::robot::RecorderReinitReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::robot::RecorderReinitRequest, ::robot::RecorderReinitReply>* streamer) {
                       return this->StreamedRecorderReinit(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecorderReinit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecorderReinit(::grpc::ServerContext* /*context*/, const ::robot::RecorderReinitRequest* /*request*/, ::robot::RecorderReinitReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecorderReinit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::robot::RecorderReinitRequest,::robot::RecorderReinitReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecorderGetState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecorderGetState() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::robot::RecorderGetStateRequest, ::robot::RecorderGetStateReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::robot::RecorderGetStateRequest, ::robot::RecorderGetStateReply>* streamer) {
                       return this->StreamedRecorderGetState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecorderGetState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecorderGetState(::grpc::ServerContext* /*context*/, const ::robot::RecorderGetStateRequest* /*request*/, ::robot::RecorderGetStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecorderGetState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::robot::RecorderGetStateRequest,::robot::RecorderGetStateReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ControlVideo<WithStreamedUnaryMethod_RecorderReinit<WithStreamedUnaryMethod_RecorderGetState<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ControlVideo<WithStreamedUnaryMethod_RecorderReinit<WithStreamedUnaryMethod_RecorderGetState<Service > > > StreamedService;
};

}  // namespace robot


#endif  // GRPC_robot_2eproto__INCLUDED
