// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: robot.proto
#ifndef GRPC_robot_2eproto__INCLUDED
#define GRPC_robot_2eproto__INCLUDED

#include "robot.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace robot {

// *
// 统一服务
class RobotService final {
 public:
  static constexpr char const* service_full_name() {
    return "robot.RobotService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Control video stream (connect/disconnect and handle SDP negotiation)
    virtual ::grpc::Status ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::robot::ControlSignalResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>> AsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>>(AsyncControlVideoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>> PrepareAsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>>(PrepareAsyncControlVideoRaw(context, request, cq));
    }
    // Query the current state and configuration of all recorders (cameras)
    virtual ::grpc::Status GetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::robot::RecorderStateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderStateResponse>> AsyncGetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderStateResponse>>(AsyncGetRecorderStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderStateResponse>> PrepareAsyncGetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderStateResponse>>(PrepareAsyncGetRecorderStateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Control video stream (connect/disconnect and handle SDP negotiation)
      virtual void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Query the current state and configuration of all recorders (cameras)
      virtual void GetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest* request, ::robot::RecorderStateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest* request, ::robot::RecorderStateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>* AsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::ControlSignalResponse>* PrepareAsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderStateResponse>* AsyncGetRecorderStateRaw(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::robot::RecorderStateResponse>* PrepareAsyncGetRecorderStateRaw(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::robot::ControlSignalResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>> AsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>>(AsyncControlVideoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>> PrepareAsyncControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>>(PrepareAsyncControlVideoRaw(context, request, cq));
    }
    ::grpc::Status GetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::robot::RecorderStateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderStateResponse>> AsyncGetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderStateResponse>>(AsyncGetRecorderStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderStateResponse>> PrepareAsyncGetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::robot::RecorderStateResponse>>(PrepareAsyncGetRecorderStateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, std::function<void(::grpc::Status)>) override;
      void ControlVideo(::grpc::ClientContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest* request, ::robot::RecorderStateResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRecorderState(::grpc::ClientContext* context, const ::robot::RecorderStateRequest* request, ::robot::RecorderStateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>* AsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::ControlSignalResponse>* PrepareAsyncControlVideoRaw(::grpc::ClientContext* context, const ::robot::ControlSignalRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::RecorderStateResponse>* AsyncGetRecorderStateRaw(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::robot::RecorderStateResponse>* PrepareAsyncGetRecorderStateRaw(::grpc::ClientContext* context, const ::robot::RecorderStateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ControlVideo_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRecorderState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Control video stream (connect/disconnect and handle SDP negotiation)
    virtual ::grpc::Status ControlVideo(::grpc::ServerContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response);
    // Query the current state and configuration of all recorders (cameras)
    virtual ::grpc::Status GetRecorderState(::grpc::ServerContext* context, const ::robot::RecorderStateRequest* request, ::robot::RecorderStateResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ControlVideo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControlVideo(::grpc::ServerContext* context, ::robot::ControlSignalRequest* request, ::grpc::ServerAsyncResponseWriter< ::robot::ControlSignalResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRecorderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRecorderState() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetRecorderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecorderState(::grpc::ServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRecorderState(::grpc::ServerContext* context, ::robot::RecorderStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::robot::RecorderStateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ControlVideo<WithAsyncMethod_GetRecorderState<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ControlVideo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::robot::ControlSignalRequest* request, ::robot::ControlSignalResponse* response) { return this->ControlVideo(context, request, response); }));}
    void SetMessageAllocatorFor_ControlVideo(
        ::grpc::MessageAllocator< ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ControlVideo(
      ::grpc::CallbackServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRecorderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRecorderState() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::robot::RecorderStateRequest, ::robot::RecorderStateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::robot::RecorderStateRequest* request, ::robot::RecorderStateResponse* response) { return this->GetRecorderState(context, request, response); }));}
    void SetMessageAllocatorFor_GetRecorderState(
        ::grpc::MessageAllocator< ::robot::RecorderStateRequest, ::robot::RecorderStateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::robot::RecorderStateRequest, ::robot::RecorderStateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRecorderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecorderState(::grpc::ServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRecorderState(
      ::grpc::CallbackServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ControlVideo<WithCallbackMethod_GetRecorderState<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ControlVideo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRecorderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRecorderState() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetRecorderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecorderState(::grpc::ServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ControlVideo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControlVideo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRecorderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRecorderState() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetRecorderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecorderState(::grpc::ServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRecorderState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ControlVideo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ControlVideo(context, request, response); }));
    }
    ~WithRawCallbackMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ControlVideo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRecorderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRecorderState() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRecorderState(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRecorderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRecorderState(::grpc::ServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRecorderState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ControlVideo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ControlVideo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::robot::ControlSignalRequest, ::robot::ControlSignalResponse>* streamer) {
                       return this->StreamedControlVideo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ControlVideo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ControlVideo(::grpc::ServerContext* /*context*/, const ::robot::ControlSignalRequest* /*request*/, ::robot::ControlSignalResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedControlVideo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::robot::ControlSignalRequest,::robot::ControlSignalResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRecorderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRecorderState() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::robot::RecorderStateRequest, ::robot::RecorderStateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::robot::RecorderStateRequest, ::robot::RecorderStateResponse>* streamer) {
                       return this->StreamedGetRecorderState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRecorderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRecorderState(::grpc::ServerContext* /*context*/, const ::robot::RecorderStateRequest* /*request*/, ::robot::RecorderStateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRecorderState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::robot::RecorderStateRequest,::robot::RecorderStateResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ControlVideo<WithStreamedUnaryMethod_GetRecorderState<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ControlVideo<WithStreamedUnaryMethod_GetRecorderState<Service > > StreamedService;
};

}  // namespace robot


#endif  // GRPC_robot_2eproto__INCLUDED
