// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ip_service.proto

#ifndef PROTOBUF_INCLUDED_ip_5fservice_2eproto
#define PROTOBUF_INCLUDED_ip_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ip_5fservice_2eproto 

namespace protobuf_ip_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ip_5fservice_2eproto
namespace ipservice {
class IpReply;
class IpReplyDefaultTypeInternal;
extern IpReplyDefaultTypeInternal _IpReply_default_instance_;
class IpRequest;
class IpRequestDefaultTypeInternal;
extern IpRequestDefaultTypeInternal _IpRequest_default_instance_;
}  // namespace ipservice
namespace google {
namespace protobuf {
template<> ::ipservice::IpReply* Arena::CreateMaybeMessage<::ipservice::IpReply>(Arena*);
template<> ::ipservice::IpRequest* Arena::CreateMaybeMessage<::ipservice::IpRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ipservice {

// ===================================================================

class IpRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ipservice.IpRequest) */ {
 public:
  IpRequest();
  virtual ~IpRequest();

  IpRequest(const IpRequest& from);

  inline IpRequest& operator=(const IpRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IpRequest(IpRequest&& from) noexcept
    : IpRequest() {
    *this = ::std::move(from);
  }

  inline IpRequest& operator=(IpRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const IpRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IpRequest* internal_default_instance() {
    return reinterpret_cast<const IpRequest*>(
               &_IpRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(IpRequest* other);
  friend void swap(IpRequest& a, IpRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IpRequest* New() const final {
    return CreateMaybeMessage<IpRequest>(NULL);
  }

  IpRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IpRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IpRequest& from);
  void MergeFrom(const IpRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IpRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // @@protoc_insertion_point(class_scope:ipservice.IpRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ip_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IpReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ipservice.IpReply) */ {
 public:
  IpReply();
  virtual ~IpReply();

  IpReply(const IpReply& from);

  inline IpReply& operator=(const IpReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IpReply(IpReply&& from) noexcept
    : IpReply() {
    *this = ::std::move(from);
  }

  inline IpReply& operator=(IpReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const IpReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IpReply* internal_default_instance() {
    return reinterpret_cast<const IpReply*>(
               &_IpReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(IpReply* other);
  friend void swap(IpReply& a, IpReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IpReply* New() const final {
    return CreateMaybeMessage<IpReply>(NULL);
  }

  IpReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IpReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IpReply& from);
  void MergeFrom(const IpReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IpReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  const ::std::string& result() const;
  void set_result(const ::std::string& value);
  #if LANG_CXX11
  void set_result(::std::string&& value);
  #endif
  void set_result(const char* value);
  void set_result(const char* value, size_t size);
  ::std::string* mutable_result();
  ::std::string* release_result();
  void set_allocated_result(::std::string* result);

  // @@protoc_insertion_point(class_scope:ipservice.IpReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr result_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ip_5fservice_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IpRequest

// string ip = 1;
inline void IpRequest::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IpRequest::ip() const {
  // @@protoc_insertion_point(field_get:ipservice.IpRequest.ip)
  return ip_.GetNoArena();
}
inline void IpRequest::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ipservice.IpRequest.ip)
}
#if LANG_CXX11
inline void IpRequest::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ipservice.IpRequest.ip)
}
#endif
inline void IpRequest::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ipservice.IpRequest.ip)
}
inline void IpRequest::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ipservice.IpRequest.ip)
}
inline ::std::string* IpRequest::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:ipservice.IpRequest.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IpRequest::release_ip() {
  // @@protoc_insertion_point(field_release:ipservice.IpRequest.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IpRequest::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:ipservice.IpRequest.ip)
}

// -------------------------------------------------------------------

// IpReply

// string result = 1;
inline void IpReply::clear_result() {
  result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& IpReply::result() const {
  // @@protoc_insertion_point(field_get:ipservice.IpReply.result)
  return result_.GetNoArena();
}
inline void IpReply::set_result(const ::std::string& value) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ipservice.IpReply.result)
}
#if LANG_CXX11
inline void IpReply::set_result(::std::string&& value) {
  
  result_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ipservice.IpReply.result)
}
#endif
inline void IpReply::set_result(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ipservice.IpReply.result)
}
inline void IpReply::set_result(const char* value, size_t size) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ipservice.IpReply.result)
}
inline ::std::string* IpReply::mutable_result() {
  
  // @@protoc_insertion_point(field_mutable:ipservice.IpReply.result)
  return result_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* IpReply::release_result() {
  // @@protoc_insertion_point(field_release:ipservice.IpReply.result)
  
  return result_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void IpReply::set_allocated_result(::std::string* result) {
  if (result != NULL) {
    
  } else {
    
  }
  result_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), result);
  // @@protoc_insertion_point(field_set_allocated:ipservice.IpReply.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ipservice

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ip_5fservice_2eproto
